In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../data/train_processed.csv')
df.head()

,file_1,file_2,real_text_id
0,The VIRSA (Visible Infrared Survey Telescope A...,The China relay network has released a signifi...,1
1,China\nThe goal of this project involves achie...,The project aims to achieve an accuracy level ...,2
2,Scientists can learn about how galaxies form a...,Dinosaur eggshells offer clues about what dino...,1
3,China\nThe study suggests that multiple star s...,The importance for understanding how stars evo...,2
4,Dinosaur Rex was excited about his new toy set...,Analyzing how fast stars rotate within a galax...,2

In [6]:
df.shape

(95, 3)

In [3]:
df_swap = pd.DataFrame()
df_swap['file_1'], df_swap['file_2'] = df['file_2'], df['file_1']
df_swap['real_text_id'] = 2 - df['real_text_id']

df_swap.head()

,file_1,file_2,real_text_id
0,The China relay network has released a signifi...,The VIRSA (Visible Infrared Survey Telescope A...,1
1,The project aims to achieve an accuracy level ...,China\nThe goal of this project involves achie...,0
2,Dinosaur eggshells offer clues about what dino...,Scientists can learn about how galaxies form a...,1
3,The importance for understanding how stars evo...,China\nThe study suggests that multiple star s...,0
4,Analyzing how fast stars rotate within a galax...,Dinosaur Rex was excited about his new toy set...,0

In [4]:
final = pd.concat([df, df_swap], axis=0)
final.head()

,file_1,file_2,real_text_id
0,The VIRSA (Visible Infrared Survey Telescope A...,The China relay network has released a signifi...,1
1,China\nThe goal of this project involves achie...,The project aims to achieve an accuracy level ...,2
2,Scientists can learn about how galaxies form a...,Dinosaur eggshells offer clues about what dino...,1
3,China\nThe study suggests that multiple star s...,The importance for understanding how stars evo...,2
4,Dinosaur Rex was excited about his new toy set...,Analyzing how fast stars rotate within a galax...,2

In [5]:
final.shape

(190, 3)

In [7]:
final.rename(columns={'file_1': 'text_1', 'file_2': 'text_2', 'real_text_id': 'label'}, inplace=True)